apiVersion: v1
kind: Secret
metadata:
  name: aws-access-keys
type: Opaque
data:
  AWS_ACCESS_KEY_ID: ACCESSKEYHERE
  AWS_SECRET_ACCESS_KEY: SECRETEKEYHERE

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: awscli-deployment
  labels:
    app: awscli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awscli
  template:
    metadata:
      labels:
        app: awscli
    spec:
      containers:
        - name: awscli
          image: kiran2361993/troubleshootingtools:v1
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-access-keys
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-access-keys
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
